checksumBehavior: update

nodeLinker: node-modules

npmScopes:
  'goatjs':
    npmRegistryServer: 'https://europe-west8-npm.pkg.dev/open-gto-2/goat/'
    npmPublishRegistry: 'https://europe-west8-npm.pkg.dev/open-gto-2/goat/'
    npmAlwaysAuth: true
